version: "3"

services:

  ghost:
    image: ghost
    volumes:
      - ./ghost_data:/var/lib/ghost/content
    ports:
      - '8080:2368'
    environment:
      - url=http://0.0.0.0:8080
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=ghostdb
      - database__connection__password=secret
      - database__connection__database=ghostdb
      - VIRTUAL_HOST=0.0.0.0:8080
      - VIRTUAL_PORT=2368
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb
    volumes:
      - ./mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=ghostdb
      - MYSQL_USER=ghostdb
      - MYSQL_PASSWORD=secret
    restart: unless-stopped